# Generated by Django 4.2.1 on 2023-08-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('chemical_id', models.IntegerField(primary_key=True, serialize=False)),
                ('inchi_value', models.CharField(max_length=10000, null=True)),
                ('pubchem_cid', models.CharField(max_length=1000, null=True)),
                ('chembl_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('taxonomy', models.CharField(max_length=5000, null=True)),
                ('ncbi_species_id', models.CharField(max_length=1000, null=True)),
                ('ncbi_subspecies_id', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XRef',
            fields=[
                ('xref_id', models.IntegerField(primary_key=True, serialize=False)),
                ('referenceCleanedDoi', models.CharField(max_length=5000, null=True)),
                ('referenceCleanedTitle', models.CharField(max_length=5000, null=True)),
                ('referenceCleanedPmcid', models.CharField(max_length=1000, null=True)),
                ('referenceCleanedPmid', models.CharField(max_length=1000, null=True)),
                ('chemical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrefs', to='herbs.chemical')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrefs', to='herbs.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_pair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drug_chembl_id', models.CharField(max_length=200, null=True)),
                ('tanimoto_similarity', models.FloatField(null=True)),
                ('target_chembl_id', models.CharField(max_length=200, null=True)),
                ('target_gene_id', models.CharField(max_length=100, null=True)),
                ('chemical_id', models.ForeignKey(db_column='chemical_id', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='herbs.chemical')),
            ],
            options={
                'db_table': 'Drugs',
            },
        ),
    ]
